language: php
php:
  - 5.6
script: phpunit test/
before_script:
  - pecl install mongodb
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install